### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by luismu78** [BracketCove/Profiler#1]
Profiler/app/google-services.json should not be syncronized. This file contains all your API settings and credentials. 

You should add it to .ignore file, revoke all the credentials, create new ones and make a new commit without this file.

Hope it helped.

**Comment by BracketCove** [comment]
Haha, that was pretty dumb in retrospect. 

I've remade the Firebase project so hopefully someone tries to use the old credentials before I have time to remove them from the Repo. 

Thank you, I appreciate your help!
