### ISSUE TITLE
Missing PhotoDetailPresenter

### ISSUE THREAD

**Issue by Elisey93** [BracketCove/Profiler#2]
I was unable to find `PhotoDetailPresenter ` in a project, while Activity, Contract and Fragment are present.
Or is that a part of a "work to be done" commit message?

**Comment by BracketCove** [comment]
Sorry about the missing file. I had two versions of the project (one version was built off camera, one mostly on camera) and there were some conflicts in merging them into one full project. Then life happened and that was like a month ago haha.

I'll be doing lots of work on Profiler today and tomorrow, so I should be able to fix this issue alongside all the others.

Cheers

**Comment by BracketCove** [comment]
Ok, added PhotoDetailPresenter.

Thanks!
